---

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directories:
    - 'src/**/*'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'pip'
    directories:
    - 'src/dockerfiles/jupyter-gap/ubuntu-2204-lts/'
    schedule:
      interval: 'daily'
