---
name: Container - build and push

on:
  pull_request: 
    paths:
      - '.github/**'
      - 'src/dockerfiles/**'
    branches: 
      - main
  schedule:
      - cron: '30 10 * * 1'
  push:
    paths:
      - '.github/**'
      - 'src/dockerfiles/**'
    branches: 
      - main

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  gap-versions:
    - 4.14.0
    - 4.13.1
    - 4.13.0
    - 4.12.2
    - 4.12.1
    - 4.12.0
  operating-systems:
    - ubuntu-2204-lts

jobs:
  build-bare:
    strategy:
      fail-fast: true
      matrix:
        gap-version: ${{ env.gap-versions }}
        operating-system-base: ${{ env.operating-systems }}
    uses: ./.github/workflows/worflow-dispatch-build.yaml
    with:
      gap-build: bare
      gap-version: ${{ matrix.gap-version }}
      operating-system-base: ${{ matrix.operating-system-base }}

  build-slim:
    needs:
      - build-bare
    strategy:
      fail-fast: true
      matrix:
        gap-version: ${{ env.gap-versions }}
        operating-system-base: ${{ env.operating-systems }}
    uses: ./.github/workflows/worflow-dispatch-build.yaml
    with:
      gap-build: slim
      gap-version: ${{ matrix.gap-version }}
      operating-system-base: ${{ matrix.operating-system-base }}

  build-full:
    needs:
      - build-bare
      - build-slim
    strategy:
      fail-fast: true
      matrix:
        gap-version: ${{ env.gap-versions }}
        operating-system-base: ${{ env.operating-systems }}
    uses: ./.github/workflows/worflow-dispatch-build.yaml
    with:
      gap-build: full
      gap-version: ${{ matrix.gap-version }}
      operating-system-base: ${{ matrix.operating-system-base }}
