---
name: Container - build and push

on:
  pull_request: 
    paths:
      - '.github/**'
      - 'src/dockerfiles/**'
    branches: 
      - main
  schedule:
      - cron: '30 10 * * 1'
  push:
    paths:
      - '.github/**'
      - 'src/dockerfiles/**'
    branches: 
      - main

jobs:
  docker-image-build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      fail-fast: true
      matrix:
        operating-system-base:
          - ubuntu-2204-lts
        gap-build:
          - bare
          - full
        gap-version:
          - 4.14.0
          - 4.13.1
          - 4.13.0
          - 4.12.2
          - 4.12.1
          - 4.12.0
    uses: ./.github/workflows/worflow-dispatch-build.yaml
    with:
      gap-version: ${{ matrix.gap-version }}
      gap-build: ${{ matrix.gap-build }}
      operating-system-base: ${{ matrix.operating-system-base }}
