---
name: build docker image

on:
  pull_request: 
    branches: 
      - main
  push:
    branches: 
      - main

jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu-2204-lts
        gap-branch:
          - master
          - stable-4.13
          - stable-4.12
        platform:
          - linux/amd64
          - linux/arm/v7
          - linux/arm64

    steps:
      - name: 👨‍💻 git -- checkout
        uses: actions/checkout@v4

      - name: 🐬 docker -- metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: 📦 docker -- login to ghcr-registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 💻 quemu -- setup
        uses: docker/setup-qemu-action@v3

      - name: 🐬 docker -- setup buildx
        uses: docker/setup-buildx-action@v3

      - name: 🐬 docker -- build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src/dockerfiles/${{ matrix.image }}
          file: ./src/dockerfiles/${{ matrix.image }}/Dockerfile
          platforms: ${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max`
          build-args: |
            PLATFORM=${{ matrix.platform }}