---
name: Container - build and push

on:
  pull_request: 
    paths:
      - '.github/**'
      - 'src/dockerfiles/**'
    branches: 
      - main
  schedule:
      - cron: '30 10 * * 1'
  push:
    paths:
      - '.github/**'
      - 'src/dockerfiles/**'
    branches: 
      - main

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.matrix.outputs.versions }}
      systems: ${{ steps.matrix.outputs.systems }}
    steps:
      - name: define - gap-versions
        id: matrix
        run: |
          echo 'systems=["ubuntu-2204-lts"]' >> "$GITHUB_OUTPUT"
          echo 'versions=["4.14.0", "4.13.1", "4.13.0", "4.12.2", "4.12.1", "4.12.0"]' >> "$GITHUB_OUTPUT"

  bare:
    needs:
      - define-matrix
    strategy:
      fail-fast: false
      matrix:
        gap-version: ${{ fromJSON(needs.define-matrix.outputs.versions) }}
        operating-system-base: ${{ fromJSON(needs.define-matrix.outputs.systems) }}
    uses: ./.github/workflows/worflow-dispatch-build.yaml
    with:
      gap-type: gap
      target: bare
      gap-version: ${{ matrix.gap-version }}
      operating-system-base: ${{ matrix.operating-system-base }}

  slim:
    needs:
      - define-matrix
      - bare
    strategy:
      fail-fast: true
      matrix:
        gap-version: ${{ fromJSON(needs.define-matrix.outputs.versions) }}
        operating-system-base: ${{ fromJSON(needs.define-matrix.outputs.systems) }}
    uses: ./.github/workflows/worflow-dispatch-build.yaml
    with:
      gap-type: gap
      target: slim
      gap-version: ${{ matrix.gap-version }}
      operating-system-base: ${{ matrix.operating-system-base }}

  full:
    needs:
      - define-matrix
      - bare
      - slim
    strategy:
      fail-fast: true
      matrix:
        gap-version: ${{ fromJSON(needs.define-matrix.outputs.versions) }}
        operating-system-base: ${{ fromJSON(needs.define-matrix.outputs.systems) }}
    uses: ./.github/workflows/worflow-dispatch-build.yaml
    with:
      gap-type: gap
      target: full
      gap-version: ${{ matrix.gap-version }}
      operating-system-base: ${{ matrix.operating-system-base }}

  jupyter:
    needs:
      - define-matrix
      - bare
      - slim
      - full
    strategy:
      fail-fast: true
      matrix:
        gap-version: ${{ fromJSON(needs.define-matrix.outputs.versions) }}
        operating-system-base: ${{ fromJSON(needs.define-matrix.outputs.systems) }}
    uses: ./.github/workflows/worflow-dispatch-build.yaml
    with:
      gap-type: jupyter-gap
      target: full
      gap-version: ${{ matrix.gap-version }}
      operating-system-base: ${{ matrix.operating-system-base }}
