---
name: Container - build and push

on:
  pull_request: 
    paths:
      - '.github/**'
      - 'src/dockerfiles/**'
    branches: 
      - main
  schedule:
      - cron: '30 10 * * 1'
  push:
    paths:
      - '.github/**'
      - 'src/dockerfiles/**'
    branches: 
      - main

jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      fail-fast: true
      matrix:
        image:
          - ubuntu-2204-lts
        gap-build:
          - bare
          - full
        gap-version:
          - 4.14.0
          - 4.13.1
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Build docker image"
        uses: ./.github/workflows/create-container.yaml
        with:
          GAP_VERSION: ${{ matrix.gap-version }}
          GAP_BUILD: ${{ matrix.gap-build }}
          GAP_BASE: ${{ matrix.image }}
